---
- name: Everday Packages
  apt: name={{ item }} state=present
  with_items:
    - curl
    - fish
    - git
    - silversearcher-ag
    - tmux
    - vim
    - virtualbox

- name: Ruby Packages
  apt: name={{ item }} state=present
  with_items:
    - libxml2
    - rake
    - ruby
    - ruby-dev

- name: Add neovim PPA repository
  apt_repository: repo='ppa:neovim-ppa/unstable'

- name: Install Neovim
  apt: name=neovim
